const build = require('./src/build-src.js');
const thesaurus = require('./src/collins.js');

let buildStopwords = function() {
  build.search('src/prepositions.txt','lib/preposition-search.js');
  build.replace('src/prepositions.txt','lib/preposition-replace.js');
  build.search('src/conjunctions.txt','lib/conjunction-search.js');
  build.replace('src/conjunctions.txt','lib/conjunction-replace.js');
  build.search('src/determiners.txt','lib/determiner-search.js');
  build.replace('src/determiners.txt','lib/determiner-replace.js');
};

let buildDictionary = function() {
  let a = build.filterWords('src/a-wordlist.txt');
  build.getWords(a,'a','lib/dictionary/raw');
  let b = build.filterWords('src/b-wordlist.txt');
  build.getWords(b,'b','lib/dictionary/raw');
  let c = build.filterWords('src/c-wordlist.txt');
  build.getWords(c,'c','lib/dictionary/raw');
  let d = build.filterWords('src/d-wordlist.txt');
  build.getWords(d,'d','lib/dictionary/raw');
  let e = build.filterWords('src/e-wordlist.txt');
  build.getWords(e,'e','lib/dictionary/raw');
  let f = build.filterWords('src/f-wordlist.txt');
  build.getWords(f,'f','lib/dictionary/raw');
  let g = build.filterWords('src/g-wordlist.txt');
  build.getWords(g,'g','lib/dictionary/raw');
  let h = build.filterWords('src/h-wordlist.txt');
  build.getWords(h,'h','lib/dictionary/raw');
  let i = build.filterWords('src/i-wordlist.txt');
  build.getWords(i,'i','lib/dictionary/raw');
  let j = build.filterWords('src/j-wordlist.txt');
  build.getWords(j,'j','lib/dictionary/raw');
  let k = build.filterWords('src/k-wordlist.txt');
  build.getWords(k,'k','lib/dictionary/raw');
  let l = build.filterWords('src/l-wordlist.txt');
  build.getWords(l,'l','lib/dictionary/raw');
  let m = build.filterWords('src/m-wordlist.txt');
  build.getWords(m,'m','lib/dictionary/raw');
  let n = build.filterWords('src/n-wordlist.txt');
  build.getWords(n,'n','lib/dictionary/raw');
  let o = build.filterWords('src/o-wordlist.txt');
  build.getWords(o,'o','lib/dictionary/raw');
  let p = build.filterWords('src/p-wordlist.txt');
  build.getWords(p,'p','lib/dictionary/raw');
  let q = build.filterWords('src/q-wordlist.txt');
  build.getWords(q,'q','lib/dictionary/raw');
  let r = build.filterWords('src/r-wordlist.txt');
  build.getWords(r,'r','lib/dictionary/raw');
  let s = build.filterWords('src/s-wordlist.txt');
  build.getWords(s,'s','lib/dictionary/raw');
  let t = build.filterWords('src/t-wordlist.txt');
  build.getWords(t,'t','lib/dictionary/raw');
  let u = build.filterWords('src/u-wordlist.txt');
  build.getWords(u,'u','lib/dictionary/raw');
  let v = build.filterWords('src/v-wordlist.txt');
  build.getWords(v,'v','lib/dictionary/raw');
  let w = build.filterWords('src/w-wordlist.txt');
  build.getWords(w,'w','lib/dictionary/raw');
  let x = build.filterWords('src/x-wordlist.txt');
  build.getWords(x,'x','lib/dictionary/raw');
  let y = build.filterWords('src/y-wordlist.txt');
  build.getWords(y,'y','lib/dictionary/raw');
  let z = build.filterWords('src/z-wordlist.txt');
  build.getWords(z,'z','lib/dictionary/raw');
};

//buildStopwords();
buildDictionary();
