const build = require('./src/build-src.js');

let buildStopwords = function() {
  build.search('src/prepositions.txt','lib/preposition-search.js');
  build.replace('src/prepositions.txt','lib/preposition-replace.js');
  build.search('src/conjunctions.txt','lib/conjunction-search.js');
  build.replace('src/conjunctions.txt','lib/conjunction-replace.js');
  build.search('src/determiners.txt','lib/determiner-search.js');
  build.replace('src/determiners.txt','lib/determiner-replace.js');
};

buildStopwords();

let buildDictionary = function() {
  let a = build.filterWords('src/a-wordlist.txt');
  build.getWords(a,'a');
  let b = build.filterWords('src/b-wordlist.txt');
  build.getWords(b,'b');
  let c = build.filterWords('src/c-wordlist.txt');
  build.getWords(c,'c');
  let d = build.filterWords('src/d-wordlist.txt');
  build.getWords(d,'d');
  let e = build.filterWords('src/e-wordlist.txt');
  build.getWords(e,'e');
  let f = build.filterWords('src/f-wordlist.txt');
  build.getWords(f,'f');
  let g = build.filterWords('src/g-wordlist.txt');
  build.getWords(g,'g');
  let h = build.filterWords('src/h-wordlist.txt');
  build.getWords(h,'h');
  let i = build.filterWords('src/i-wordlist.txt');
  build.getWords(i,'i');
  let j = build.filterWords('src/j-wordlist.txt');
  build.getWords(j,'j');
  let k = build.filterWords('src/k-wordlist.txt');
  build.getWords(k,'k');
  let l = build.filterWords('src/l-wordlist.txt');
  build.getWords(l,'l');
  let m = build.filterWords('src/m-wordlist.txt');
  build.getWords(m,'m');
  let n = build.filterWords('src/n-wordlist.txt');
  build.getWords(n,'n');
  let o = build.filterWords('src/o-wordlist.txt');
  build.getWords(o,'o');
  let p = build.filterWords('src/p-wordlist.txt');
  build.getWords(p,'p');
  let q = build.filterWords('src/q-wordlist.txt');
  build.getWords(q,'q');
  let r = build.filterWords('src/r-wordlist.txt');
  build.getWords(r,'r');
  let s = build.filterWords('src/s-wordlist.txt');
  build.getWords(s,'s');
  let t = build.filterWords('src/t-wordlist.txt');
  build.getWords(t,'t');
  let u = build.filterWords('src/u-wordlist.txt');
  build.getWords(u,'u');
  let v = build.filterWords('src/v-wordlist.txt');
  build.getWords(v,'v');
  let w = build.filterWords('src/w-wordlist.txt');
  build.getWords(w,'w');
  let x = build.filterWords('src/x-wordlist.txt');
  build.getWords(x,'x');
  let y = build.filterWords('src/y-wordlist.txt');
  build.getWords(y,'y');
  let z = build.filterWords('src/z-wordlist.txt');
  build.getWords(z,'z');
};
