const pos = require('./index.js');
pos.init();
pos.unset(['noun','preposition']);
let line = pos.snippets(['Be kind but a little firm.',
       'Use a harness instead of a choke chain.',
       'When using voice commands, use a firm voice.',
       'You mean for this dog to sit, so speak with meaning.',
       'Do not continue to repeat a command over and over again hoping the dog will eventually perform the command.',
       'Reinforce the command within two to three seconds if the command is not done and then praise the dog.',
       'You don\'t want to be one of those people you see repeating "sit" 20 or so times until the dog sits.',
       'You want a sit on the first command, not the twentieth.',
       'Do not allow your dog to bite you, even playfully.',
       'This sets a bad precedent and it will be difficult for you to break them of this habit.',
       'Dangerous, aggressive dogs will need special training from an experienced dog trainer.',
       'In some cases, a veterinary behaviorist will need to become involved.',
       'At no time should you take on an aggressive dog without the proper training.',
       'It is too dangerous.',
       'Remember that every dog is different.',
       'One dog might learn at a slower pace than another dog, and that\'s okay.',
       'There is no such thing as an untrainable dog!',
       'Remember that dogs do not communicate the same way humans do.',
       'Do not let your dog "lean" on you either when you are standing up or sitting down.',
       'This is not a sign that they like you.',
       'This is a sign of dominance.',
       'The dog is encroaching into your space.',
       'You are the leader.',
       'Stand up and let your knee or foot nudge them out of your space.',
       'Praise the dog for getting up.',
       'Give the dog a command to lay down on their bed or go to their crate if you need to manage your personal space more effectively.',
       'If using hand signals, be sure they are unique and distinct for the dog to see and differentiate.',
       'There are standard dog training signals used for basic commands like "sit," "stay," etc.',
       'If you are unsure, ask your trainer or look online or in a book for a clearer picture of the body language to use.',
       'Be consistent.',
       'Make sure the command and hand signal use is the same each time.',
       'If your dog is out of control, another good way to correct the behavior is to isolate them from the rest of the "pack".',
       'Put them in their crate or kennel and ignore them.',
       'They may whine and howl, but you have to ignore it.',
       'Think of it as a "time out" for your dog.',
       'When they are quiet and settled, let them out of the crate.',
       'Don\'t forget to keep your dog exercised to help manage their energy level.',
       'Playing "fetch" is a great way to get the dog tired.',
       'Praise your dog often and lavishly.',
       'Training dogs requires a large amount of patience.',
       'It can be frustrating if you choose a breed wrong for your skill level or lifestyle.',
       'If you find you have made a poor choice, ask professionals for guidance.',
       'You may need to find a new home for the dog.',
       'Call your local rescue organization or veterinarian.',
       'Don\'t wait until you and the dog have suffered.',
       'If you just don\'t have the patience, then get yourself some personal one-on-one training from a reputable dog trainer.',
       'Nobody is a "born" dog trainer without getting educated.',
       'Don\'t be cruel to your dog or hit them.',
       'If you strike your dog out of frustration, he will only learn to fear you.',
       'Clean up after your dog if they defecate on someone else\'s property or in a public place.'],0,0,0,1);
console.log(pos.title('non shedding dogs','p','tips'));
