const pos = require('./index.js');
pos.init();
console.log(pos.title('training a dog','g','facts',9));
console.log(pos.promo('training a dog','http://heartmydog.com'));
console.log(pos.intro('facts',['dog training','training a dog']));
console.log(pos.license(true));
console.log(pos.tags(['dog training','training a dog']));
console.log(pos.snippet('Dog training is a thing many people want to learn about. A few of the more interesting tidbits when it comes to training a dog are talked about in this video. Please like and share this video with anyone interested in dog training!',0,1,1));
let sentences = ['this is a first sentence','this is a second sentence.'];
let print = pos.print(sentences,true,false,true,false);
let snippets = pos.snippets(sentences,true,true,true,true);
console.log(print);
console.log(snippets);
